import type { Title } from "./types";

export const GENRES = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Drama",
  "Fantasy",
  "Horror",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "Superhero",
  "Historical",
  "Slice of Life",
] as const;

export const titles: Title[] = [
  // ───────────────────────── MOVIES ─────────────────────────
  {
    id: "inception",
    type: "movie",
    title: "Inception",
    year: "2010",
    rating: 8.8,
    runtime: "2h 28m",
    genres: ["Sci-Fi", "Thriller", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/ii8QGacT3MXESqBckQlyrATY0lT.jpg",
    overview:
      "Cobb steals information from the dreams of targets, allowing him to plant ideas. Given the chance to be pardoned, he must pull off the perfect inception — an idea planted in the mind of a corporate heir.",
    tagline: "Your mind is the scene of the crime.",
    cast: [
      { name: "Leonardo DiCaprio", role: "Dom Cobb" },
      { name: "Joseph Gordon-Levitt", role: "Arthur" },
      { name: "Elliot Page", role: "Ariadne" },
      { name: "Tom Hardy", role: "Eames" },
      { name: "Ken Watanabe", role: "Saito" },
      { name: "Marion Cotillard", role: "Mal" },
    ],
    featured: true,
  },
  {
    id: "interstellar",
    type: "movie",
    title: "Interstellar",
    year: "2014",
    rating: 8.7,
    runtime: "2h 49m",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/8sNiAPPYU14PUepFNeSNGUTiHW.jpg",
    overview:
      "As Earth becomes uninhabitable, a team of explorers travels through a wormhole in search of a new home for humanity — and a father races time and space to return to the daughter he left behind.",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    cast: [
      { name: "Matthew McConaughey", role: "Cooper" },
      { name: "Anne Hathaway", role: "Brand" },
      { name: "Jessica Chastain", role: "Murph" },
      { name: "Michael Caine", role: "Professor Brand" },
      { name: "Mackenzie Foy", role: "Young Murph" },
    ],
    featured: true,
  },
  {
    id: "the-dark-knight",
    type: "movie",
    title: "The Dark Knight",
    year: "2008",
    rating: 9.0,
    runtime: "2h 32m",
    genres: ["Action", "Crime", "Thriller", "Superhero"],
    poster: "https://media.themoviedb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg",
    overview:
      "Batman faces his most chaotic adversary yet: the Joker, an agent of anarchy determined to tear Gotham City apart — and prove that even the most noble soul can be broken.",
    tagline: "The Dark Knight rises. The Joker comes.",
    cast: [
      { name: "Christian Bale", role: "Bruce Wayne" },
      { name: "Heath Ledger", role: "The Joker" },
      { name: "Aaron Eckhart", role: "Harvey Dent" },
      { name: "Gary Oldman", role: "Commissioner Gordon" },
      { name: "Michael Caine", role: "Alfred" },
    ],
    featured: true,
  },
  {
    id: "the-godfather",
    type: "movie",
    title: "The Godfather",
    year: "1972",
    rating: 9.2,
    runtime: "2h 55m",
    genres: ["Crime", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg",
    overview:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son — sparking a brutal saga of power, loyalty and betrayal.",
    tagline: "An offer he can't refuse.",
    cast: [
      { name: "Marlon Brando", role: "Don Vito Corleone" },
      { name: "Al Pacino", role: "Michael Corleone" },
      { name: "James Caan", role: "Sonny Corleone" },
      { name: "Robert Duvall", role: "Tom Hagen" },
      { name: "Diane Keaton", role: "Kay Adams" },
    ],
  },
  {
    id: "pulp-fiction",
    type: "movie",
    title: "Pulp Fiction",
    year: "1994",
    rating: 8.9,
    runtime: "2h 34m",
    genres: ["Crime", "Drama", "Thriller"],
    poster: "https://media.themoviedb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    overview:
      "The lives of two hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption told out of order.",
    tagline: "You won't know the facts until you've seen the fiction.",
    cast: [
      { name: "John Travolta", role: "Vincent Vega" },
      { name: "Samuel L. Jackson", role: "Jules Winnfield" },
      { name: "Uma Thurman", role: "Mia Wallace" },
      { name: "Bruce Willis", role: "Butch Coolidge" },
      { name: "Tim Roth", role: "Pumpkin" },
    ],
  },
  {
    id: "the-shawshank-redemption",
    type: "movie",
    title: "The Shawshank Redemption",
    year: "1994",
    rating: 9.3,
    runtime: "2h 22m",
    genres: ["Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/v8xVDqt8uCul3c3mgx4VpGCwxJC.jpg",
    overview:
      "Falsely accused of murder, banker Andy Dufresne endures two decades of prison life — forging an unbreakable friendship and a quietly unshakeable hope.",
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    cast: [
      { name: "Tim Robbins", role: "Andy Dufresne" },
      { name: "Morgan Freeman", role: "Ellis \"Red\" Redding" },
      { name: "Bob Gunton", role: "Warden Norton" },
      { name: "William Sadler", role: "Heywood" },
    ],
  },
  {
    id: "fight-club",
    type: "movie",
    title: "Fight Club",
    year: "1999",
    rating: 8.8,
    runtime: "2h 19m",
    genres: ["Drama", "Thriller"],
    poster: "https://media.themoviedb.org/t/p/w500/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/c6OLXfKAk5BKeR6broC8pYiCquX.jpg",
    overview:
      "An insomniac office worker and a devil-may-care soap maker form an underground fight club that spirals into something much more dangerous.",
    tagline: "Mischief. Mayhem. Soap.",
    cast: [
      { name: "Brad Pitt", role: "Tyler Durden" },
      { name: "Edward Norton", role: "The Narrator" },
      { name: "Helena Bonham Carter", role: "Marla Singer" },
      { name: "Meat Loaf", role: "Robert Paulson" },
    ],
  },
  {
    id: "the-matrix",
    type: "movie",
    title: "The Matrix",
    year: "1999",
    rating: 8.7,
    runtime: "2h 16m",
    genres: ["Sci-Fi", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/lrtSb1skJayPydZk0OSMAKjBOVe.jpg",
    overview:
      "A hacker discovers reality is a simulation built by machines — and that he may be the chosen one to set humanity free.",
    tagline: "Welcome to the Real World.",
    cast: [
      { name: "Keanu Reeves", role: "Neo" },
      { name: "Laurence Fishburne", role: "Morpheus" },
      { name: "Carrie-Anne Moss", role: "Trinity" },
      { name: "Hugo Weaving", role: "Agent Smith" },
    ],
  },
  {
    id: "titanic",
    type: "movie",
    title: "Titanic",
    year: "1997",
    rating: 7.9,
    runtime: "3h 14m",
    genres: ["Romance", "Drama", "Historical"],
    poster: "https://media.themoviedb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/xXCuto8YVp5RFqBJ7yKmVmLOWpF.jpg",
    overview:
      "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic — a romance doomed to be tested by tragedy.",
    tagline: "Nothing on Earth could come between them.",
    cast: [
      { name: "Leonardo DiCaprio", role: "Jack Dawson" },
      { name: "Kate Winslet", role: "Rose DeWitt Bukater" },
      { name: "Billy Zane", role: "Cal Hockley" },
      { name: "Kathy Bates", role: "Molly Brown" },
    ],
  },
  {
    id: "avatar",
    type: "movie",
    title: "Avatar",
    year: "2009",
    rating: 7.9,
    runtime: "2h 42m",
    genres: ["Sci-Fi", "Adventure", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
    overview:
      "A paralyzed marine is sent to the lush alien world of Pandora on a sensitive mission — but becomes torn between following orders and protecting the people he has come to love.",
    tagline: "Enter the world of Pandora.",
    cast: [
      { name: "Sam Worthington", role: "Jake Sully" },
      { name: "Zoe Saldana", role: "Neytiri" },
      { name: "Sigourney Weaver", role: "Dr. Grace Augustine" },
      { name: "Stephen Lang", role: "Colonel Quaritch" },
    ],
  },
  {
    id: "avengers-endgame",
    type: "movie",
    title: "Avengers: Endgame",
    year: "2019",
    rating: 8.4,
    runtime: "3h 1m",
    genres: ["Superhero", "Action", "Sci-Fi"],
    poster: "https://media.themoviedb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    overview:
      "After the devastating snap, the remaining Avengers assemble once more — and will go to any length to undo what Thanos has done and restore balance to the universe.",
    tagline: "Part of the journey is the end.",
    cast: [
      { name: "Robert Downey Jr.", role: "Iron Man" },
      { name: "Chris Evans", role: "Captain America" },
      { name: "Chris Hemsworth", role: "Thor" },
      { name: "Scarlett Johansson", role: "Black Widow" },
      { name: "Jeremy Renner", role: "Hawkeye" },
    ],
  },
  {
    id: "parasite",
    type: "movie",
    title: "Parasite",
    year: "2019",
    rating: 8.5,
    runtime: "2h 12m",
    genres: ["Thriller", "Drama", "Comedy"],
    poster: "https://media.themoviedb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    overview:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan — with devastating consequences.",
    tagline: "Act like you own the place.",
    cast: [
      { name: "Song Kang-ho", role: "Ki-taek" },
      { name: "Cho Yeo-jeong", role: "Yeon-kyo" },
      { name: "Choi Woo-shik", role: "Ki-woo" },
      { name: "Park So-dam", role: "Ki-jung" },
    ],
  },
  {
    id: "whiplash",
    type: "movie",
    title: "Whiplash",
    year: "2014",
    rating: 8.5,
    runtime: "1h 47m",
    genres: ["Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
    overview:
      "A promising young drummer enrolls at a cutthroat music conservatory where his dreams are mentored — and terrorized — by an instructor who will stop at nothing to realize a student's potential.",
    tagline: "The road to greatness can take you to the edge.",
    cast: [
      { name: "Miles Teller", role: "Andrew Neiman" },
      { name: "J.K. Simmons", role: "Terence Fletcher" },
      { name: "Melissa Benoist", role: "Nicole" },
      { name: "Paul Reiser", role: "Jim Neiman" },
    ],
  },
  {
    id: "la-la-land",
    type: "movie",
    title: "La La Land",
    year: "2016",
    rating: 8.0,
    runtime: "2h 8m",
    genres: ["Romance", "Drama", "Comedy"],
    poster: "https://media.themoviedb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg",
    overview:
      "An aspiring actress and a jazz pianist chase their dreams in Los Angeles — and fall in love while learning that it isn't easy to follow both your heart and your ambition.",
    tagline: "Here's to the fools who dream.",
    cast: [
      { name: "Ryan Gosling", role: "Sebastian Wilder" },
      { name: "Emma Stone", role: "Mia Dolan" },
      { name: "John Legend", role: "Keith" },
      { name: "Rosemarie DeWitt", role: "Laura" },
    ],
  },
  {
    id: "the-grand-budapest-hotel",
    type: "movie",
    title: "The Grand Budapest Hotel",
    year: "2014",
    rating: 8.1,
    runtime: "1h 39m",
    genres: ["Comedy", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/jK65srQczOKTpW62wPxwwKztGgE.jpg",
    overview:
      "A legendary concierge and his trusted lobby boy become entangled in the theft of a priceless painting and the battle for an enormous family fortune.",
    tagline: "A grand adventure.",
    cast: [
      { name: "Ralph Fiennes", role: "M. Gustave" },
      { name: "Tony Revolori", role: "Zero Moustafa" },
      { name: "Saoirse Ronan", role: "Agatha" },
      { name: "Adrien Brody", role: "Dmitri" },
      { name: "Willem Dafoe", role: "Jopling" },
    ],
  },
  {
    id: "the-batman",
    type: "movie",
    title: "The Batman",
    year: "2022",
    rating: 7.8,
    runtime: "2h 56m",
    genres: ["Superhero", "Crime", "Thriller"],
    poster: "https://media.themoviedb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/rvtdN5XkWAfGX6xDuPL6yYS2seK.jpg",
    overview:
      "In his second year fighting crime, Batman unearths corruption in Gotham City while pursuing the Riddler, a serial killer who leaves a trail of cryptic puzzles.",
    tagline: "Uncover the truth.",
    cast: [
      { name: "Robert Pattinson", role: "Bruce Wayne" },
      { name: "Zoë Kravitz", role: "Selina Kyle" },
      { name: "Paul Dano", role: "The Riddler" },
      { name: "Jeffrey Wright", role: "Commissioner Gordon" },
      { name: "Colin Farrell", role: "The Penguin" },
    ],
  },
  {
    id: "joker",
    type: "movie",
    title: "Joker",
    year: "2019",
    rating: 8.4,
    runtime: "2h 2m",
    genres: ["Crime", "Thriller", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/rlay2M5QYvi6igbGcFjq8jxeusY.jpg",
    overview:
      "In Gotham's fractured society, a mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic criminal mastermind.",
    tagline: "Put on a happy face.",
    cast: [
      { name: "Joaquin Phoenix", role: "Arthur Fleck" },
      { name: "Robert De Niro", role: "Murray Franklin" },
      { name: "Zazie Beetz", role: "Sophie Dumond" },
      { name: "Frances Conroy", role: "Penny Fleck" },
    ],
  },
  {
    id: "oppenheimer",
    type: "movie",
    title: "Oppenheimer",
    year: "2023",
    rating: 8.3,
    runtime: "3h 0m",
    genres: ["Drama", "Historical"],
    poster: "https://media.themoviedb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/7CENyUim29IEsaJhUxIGymCRvPu.jpg",
    overview:
      "The story of J. Robert Oppenheimer, the brilliant physicist whose leadership of the Manhattan Project built the atomic bomb — and whose conscience would forever be haunted by it.",
    tagline: "The world forever changes.",
    cast: [
      { name: "Cillian Murphy", role: "J. Robert Oppenheimer" },
      { name: "Emily Blunt", role: "Kitty Oppenheimer" },
      { name: "Robert Downey Jr.", role: "Lewis Strauss" },
      { name: "Matt Damon", role: "Leslie Groves" },
    ],
  },
  {
    id: "dune-part-two",
    type: "movie",
    title: "Dune: Part Two",
    year: "2024",
    rating: 8.5,
    runtime: "2h 46m",
    genres: ["Sci-Fi", "Adventure", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/eZ239CUp1d6OryZEBPnO2n87gMG.jpg",
    overview:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family — facing a choice between the love of his life and the fate of the known universe.",
    tagline: "Long live the fighters.",
    cast: [
      { name: "Timothée Chalamet", role: "Paul Atreides" },
      { name: "Zendaya", role: "Chani" },
      { name: "Rebecca Ferguson", role: "Lady Jessica" },
      { name: "Javier Bardem", role: "Stilgar" },
      { name: "Austin Butler", role: "Feyd-Rautha" },
    ],
    featured: true,
  },
  {
    id: "barbie",
    type: "movie",
    title: "Barbie",
    year: "2023",
    rating: 7.0,
    runtime: "1h 54m",
    genres: ["Comedy", "Adventure", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/1esAE8sLJRWWFsLLeh5r3g2WanI.jpg",
    overview:
      "Barbie suffers a crisis that leads her to question her world and her existence, and she sets off on a journey to the real world — with Ken in tow — to discover the truth about humanity.",
    tagline: "She's having the time of her life.",
    cast: [
      { name: "Margot Robbie", role: "Barbie" },
      { name: "Ryan Gosling", role: "Ken" },
      { name: "America Ferrera", role: "Gloria" },
      { name: "Will Ferrell", role: "CEO of Mattel" },
    ],
  },
  {
    id: "top-gun-maverick",
    type: "movie",
    title: "Top Gun: Maverick",
    year: "2022",
    rating: 8.3,
    runtime: "2h 10m",
    genres: ["Action", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
    overview:
      "After more than thirty years of service as one of the Navy's top aviators, Pete \"Maverick\" Mitchell confronts his past while training a new generation of Top Gun graduates for a dangerous mission.",
    tagline: "Feel the need. The need for speed.",
    cast: [
      { name: "Tom Cruise", role: "Pete \"Maverick\" Mitchell" },
      { name: "Miles Teller", role: "Lt. Bradley Bradshaw" },
      { name: "Jennifer Connelly", role: "Penny Benjamin" },
      { name: "Val Kilmer", role: "Adm. Tom \"Iceman\" Kazansky" },
    ],
  },
  {
    id: "spider-man-no-way-home",
    type: "movie",
    title: "Spider-Man: No Way Home",
    year: "2021",
    rating: 8.3,
    runtime: "2h 28m",
    genres: ["Superhero", "Action", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    overview:
      "When a spell goes wrong, villains from every dimension start entering Peter Parker's world — and he must face the consequences of an identity no longer his to keep secret.",
    tagline: "The Multiverse unleashed.",
    cast: [
      { name: "Tom Holland", role: "Peter Parker" },
      { name: "Zendaya", role: "M.J." },
      { name: "Benedict Cumberbatch", role: "Doctor Strange" },
      { name: "Tobey Maguire", role: "Peter Parker" },
      { name: "Andrew Garfield", role: "Peter Parker" },
    ],
  },
  {
    id: "lord-of-the-rings-fellowship",
    type: "movie",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: "2001",
    rating: 8.8,
    runtime: "2h 58m",
    genres: ["Fantasy", "Adventure", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/oiwc338EoBgS4sEI2ixAny4KQKg.jpg",
    overview:
      "A young hobbit named Frodo inherits the One Ring, an object of immense power that must be destroyed in the fires of Mount Doom — and sets out with the Fellowship to save Middle-earth.",
    tagline: "Fate has chosen him.",
    cast: [
      { name: "Elijah Wood", role: "Frodo Baggins" },
      { name: "Ian McKellen", role: "Gandalf" },
      { name: "Viggo Mortensen", role: "Aragorn" },
      { name: "Sean Astin", role: "Samwise Gamgee" },
      { name: "Liv Tyler", role: "Arwen" },
    ],
  },
  {
    id: "mad-max-fury-road",
    type: "movie",
    title: "Mad Max: Fury Road",
    year: "2015",
    rating: 8.1,
    runtime: "2h 0m",
    genres: ["Action", "Sci-Fi", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg",
    overview:
      "In a post-apocalyptic wasteland, Max teams up with Imperator Furiosa to escape a warlord and help a small group of women cross the desert to freedom.",
    tagline: "What a lovely day.",
    cast: [
      { name: "Tom Hardy", role: "Max Rockatansky" },
      { name: "Charlize Theron", role: "Imperator Furiosa" },
      { name: "Nicholas Hoult", role: "Nux" },
      { name: "Hugh Keays-Byrne", role: "Immortan Joe" },
    ],
  },
  {
    id: "dune",
    type: "movie",
    title: "Dune",
    year: "2021",
    rating: 8.0,
    runtime: "2h 35m",
    genres: ["Sci-Fi", "Adventure", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/zRKQW58MBEY078AxkHxEJzUskCl.jpg",
    overview:
      "Paul Atreides, heir to a noble family, must travel to the most dangerous planet in the universe to secure his family's future, as forces conspire to ensure the failure of his destiny.",
    tagline: "Beyond fear, destiny awaits.",
    cast: [
      { name: "Timothée Chalamet", role: "Paul Atreides" },
      { name: "Rebecca Ferguson", role: "Lady Jessica" },
      { name: "Oscar Isaac", role: "Duke Leto" },
      { name: "Zendaya", role: "Chani" },
    ],
  },
  {
    id: "spider-man-into-the-spider-verse",
    type: "movie",
    title: "Spider-Man: Into the Spider-Verse",
    year: "2018",
    rating: 8.4,
    runtime: "1h 57m",
    genres: ["Animation", "Superhero", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/1ntePsIqeklfmrQJqZPncCydsqY.jpg",
    overview:
      "Miles Morales becomes Spider-Man and must team up with spider-powered heroes from other dimensions to stop a threat to all realities — in a mind-melting, groundbreaking animation style.",
    tagline: "More than one wears the mask.",
    cast: [
      { name: "Shameik Moore", role: "Miles Morales" },
      { name: "Jake Johnson", role: "Peter B. Parker" },
      { name: "Hailee Steinfeld", role: "Gwen Stacy" },
      { name: "Nicolas Cage", role: "Spider-Man Noir" },
    ],
  },
  {
    id: "the-social-network",
    type: "movie",
    title: "The Social Network",
    year: "2010",
    rating: 7.8,
    runtime: "2h 0m",
    genres: ["Drama", "Historical"],
    poster: "https://media.themoviedb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/1PXwh3nJzgRkkYnqfWInJNypeL4.jpg",
    overview:
      "The story of the founding of Facebook, and how Harvard undergrad Mark Zuckerberg went from lonely coding prodigy to creator of a global phenomenon — while alienating his closest friends.",
    tagline: "You don't get to 500 million friends without making a few enemies.",
    cast: [
      { name: "Jesse Eisenberg", role: "Mark Zuckerberg" },
      { name: "Andrew Garfield", role: "Eduardo Saverin" },
      { name: "Justin Timberlake", role: "Sean Parker" },
      { name: "Armie Hammer", role: "Winklevoss" },
    ],
  },
  {
    id: "gladiator",
    type: "movie",
    title: "Gladiator",
    year: "2000",
    rating: 8.5,
    runtime: "2h 35m",
    genres: ["Action", "Drama", "Historical"],
    poster: "https://media.themoviedb.org/t/p/w500/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/Ar7QuJ7sJEiC0oP3I8fKBKIQD9u.jpg",
    overview:
      "A betrayed Roman general, sold into slavery and trained as a gladiator, rises through the ranks to confront the corrupt emperor who murdered his family.",
    tagline: "What we do in life echoes in eternity.",
    cast: [
      { name: "Russell Crowe", role: "Maximus Decimus Meridius" },
      { name: "Joaquin Phoenix", role: "Commodus" },
      { name: "Connie Nielsen", role: "Lucilla" },
      { name: "Oliver Reed", role: "Proximo" },
    ],
  },
  {
    id: "everything-everywhere-all-at-once",
    type: "movie",
    title: "Everything Everywhere All at Once",
    year: "2022",
    rating: 7.9,
    runtime: "2h 19m",
    genres: ["Sci-Fi", "Comedy", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg",
    overview:
      "An exhausted Chinese-American woman is swept into a wild adventure where she alone can save the multiverse by connecting with the many lives she could have led.",
    tagline: "The universe is so much bigger than you realize.",
    cast: [
      { name: "Michelle Yeoh", role: "Evelyn Wang" },
      { name: "Ke Huy Quan", role: "Waymond Wang" },
      { name: "Stephanie Hsu", role: "Joy Wang" },
      { name: "Jamie Lee Curtis", role: "Deirdre Beaubeirdra" },
    ],
  },
  {
    id: "jurassic-park",
    type: "movie",
    title: "Jurassic Park",
    year: "1993",
    rating: 8.2,
    runtime: "2h 7m",
    genres: ["Sci-Fi", "Adventure", "Thriller"],
    poster: "https://media.themoviedb.org/t/p/w500/63viWuPfYQjRYLSZSZNq7dglJP5.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/4SyDTF02R5BepqSdQmOaNCHObzF.jpg",
    overview:
      "Scientists create a theme park of cloned dinosaurs on a remote island — and must survive when the park's security systems collapse and the prehistoric creatures break loose.",
    tagline: "An adventure 65 million years in the making.",
    cast: [
      { name: "Sam Neill", role: "Dr. Alan Grant" },
      { name: "Laura Dern", role: "Dr. Ellie Sattler" },
      { name: "Jeff Goldblum", role: "Dr. Ian Malcolm" },
      { name: "Richard Attenborough", role: "John Hammond" },
    ],
  },
  // ───────────────────────── TV SERIES ─────────────────────────
  {
    id: "breaking-bad",
    type: "tv",
    title: "Breaking Bad",
    year: "2008",
    rating: 9.5,
    runtime: "47m / ep",
    genres: ["Crime", "Drama", "Thriller"],
    poster: "https://media.themoviedb.org/t/p/w500/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    overview:
      "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    tagline: "Change the equation.",
    creator: "Vince Gilligan",
    status: "Ended",
    seasons: 5,
    episodes: 62,
    cast: [
      { name: "Bryan Cranston", role: "Walter White" },
      { name: "Aaron Paul", role: "Jesse Pinkman" },
      { name: "Anna Gunn", role: "Skyler White" },
      { name: "Dean Norris", role: "Hank Schrader" },
      { name: "Bob Odenkirk", role: "Saul Goodman" },
    ],
    featured: true,
  },
  {
    id: "stranger-things",
    type: "tv",
    title: "Stranger Things",
    year: "2016",
    rating: 8.7,
    runtime: "50m / ep",
    genres: ["Sci-Fi", "Mystery", "Horror"],
    poster: "https://media.themoviedb.org/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    overview:
      "When a young boy disappears, his small town unravels a series of mysteries involving secret experiments, terrifying otherworldly forces and one strange little girl.",
    tagline: "It's Hawkins, Indiana. Strange things are happening.",
    creator: "The Duffer Brothers",
    status: "Ended",
    seasons: 5,
    episodes: 42,
    cast: [
      { name: "Millie Bobby Brown", role: "Eleven" },
      { name: "Finn Wolfhard", role: "Mike Wheeler" },
      { name: "Winona Ryder", role: "Joyce Byers" },
      { name: "David Harbour", role: "Jim Hopper" },
      { name: "Natalia Dyer", role: "Nancy Wheeler" },
    ],
    featured: true,
  },
  {
    id: "game-of-thrones",
    type: "tv",
    title: "Game of Thrones",
    year: "2011",
    rating: 9.2,
    runtime: "57m / ep",
    genres: ["Fantasy", "Drama", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
    overview:
      "Noble families fight for control of the Iron Throne in the Seven Kingdoms of Westeros, while an ancient enemy awakens beyond the Wall and threatens all of humanity.",
    tagline: "Winter is coming.",
    creator: "David Benioff & D.B. Weiss",
    status: "Ended",
    seasons: 8,
    episodes: 73,
    cast: [
      { name: "Emilia Clarke", role: "Daenerys Targaryen" },
      { name: "Kit Harington", role: "Jon Snow" },
      { name: "Peter Dinklage", role: "Tyrion Lannister" },
      { name: "Lena Headey", role: "Cersei Lannister" },
      { name: "Maisie Williams", role: "Arya Stark" },
    ],
  },
  {
    id: "the-mandalorian",
    type: "tv",
    title: "The Mandalorian",
    year: "2019",
    rating: 8.7,
    runtime: "39m / ep",
    genres: ["Sci-Fi", "Adventure", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/9zcbqSxdsRMZWHYtyCd1nXPr2xq.jpg",
    overview:
      "A lone bounty hunter in the outer reaches of the galaxy goes on the run after being hired to retrieve the mysterious, Force-sensitive creature known as Grogu.",
    tagline: "Bring the child. Fight the empire.",
    creator: "Jon Favreau",
    status: "Returning",
    seasons: 3,
    episodes: 24,
    cast: [
      { name: "Pedro Pascal", role: "The Mandalorian" },
      { name: "Giancarlo Esposito", role: "Moff Gideon" },
      { name: "Carl Weathers", role: "Greef Karga" },
      { name: "Katee Sackhoff", role: "Bo-Katan Kryze" },
    ],
  },
  {
    id: "squid-game",
    type: "tv",
    title: "Squid Game",
    year: "2021",
    rating: 8.0,
    runtime: "55m / ep",
    genres: ["Thriller", "Drama", "Mystery"],
    poster: "https://media.themoviedb.org/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games — with deadly consequences and a tempting 45.6 billion won prize.",
    tagline: "45.6 billion won. Six games. One winner.",
    creator: "Hwang Dong-hyuk",
    status: "Returning",
    seasons: 2,
    episodes: 16,
    cast: [
      { name: "Lee Jung-jae", role: "Seong Gi-hun" },
      { name: "Park Hae-soo", role: "Cho Sang-woo" },
      { name: "Wi Ha-joon", role: "Hwang Jun-ho" },
      { name: "Jung Ho-yeon", role: "Kang Sae-byeok" },
    ],
  },
  {
    id: "the-office",
    type: "tv",
    title: "The Office",
    year: "2005",
    rating: 8.9,
    runtime: "22m / ep",
    genres: ["Comedy"],
    poster: "https://media.themoviedb.org/t/p/w500/dg9e5fPRRId8PoBE0F6jl5y85Eu.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/mLyW3UTgi2lsMdtueYODcfAB9Ku.jpg",
    overview:
      "A mockumentary look at the lives of the employees working at Dunder Mifflin's Scranton, Pennsylvania branch — led by the cringe-worthy yet lovable regional manager Michael Scott.",
    tagline: "Work is a zoo.",
    creator: "Greg Daniels",
    status: "Ended",
    seasons: 9,
    episodes: 201,
    cast: [
      { name: "Steve Carell", role: "Michael Scott" },
      { name: "John Krasinski", role: "Jim Halpert" },
      { name: "Jenna Fischer", role: "Pam Beesly" },
      { name: "Rainn Wilson", role: "Dwight Schrute" },
    ],
  },
  {
    id: "wednesday",
    type: "tv",
    title: "Wednesday",
    year: "2022",
    rating: 8.1,
    runtime: "48m / ep",
    genres: ["Comedy", "Mystery", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    overview:
      "Wednesday Addams investigates a monstrous mystery at her new boarding school, Nevermore Academy — while developing her psychic powers and making unlikely allies.",
    tagline: "Every day is Hump Day.",
    creator: "Alfred Gough & Miles Millar",
    status: "Returning",
    seasons: 2,
    episodes: 16,
    cast: [
      { name: "Jenna Ortega", role: "Wednesday Addams" },
      { name: "Emma Myers", role: "Enid Sinclair" },
      { name: "Catherine Zeta-Jones", role: "Morticia Addams" },
      { name: "Luis Guzmán", role: "Gomez Addams" },
    ],
  },
  {
    id: "house-of-the-dragon",
    type: "tv",
    title: "House of the Dragon",
    year: "2022",
    rating: 8.4,
    runtime: "55m / ep",
    genres: ["Fantasy", "Drama", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/7V0Ebks0GgpKvQ7QbLAIdX5dos4.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/577eXC8wFQT0eUrJcgznSiFPRmk.jpg",
    overview:
      "Two hundred years before Game of Thrones, the Targaryen dynasty is at its zenith — until an internal succession war over the Iron Throne ignites a brutal civil conflict.",
    tagline: "Dragons dance.",
    creator: "Ryan Condal & George R.R. Martin",
    status: "Returning",
    seasons: 2,
    episodes: 18,
    cast: [
      { name: "Emma D'Arcy", role: "Rhaenyra Targaryen" },
      { name: "Matt Smith", role: "Daemon Targaryen" },
      { name: "Olivia Cooke", role: "Alicent Hightower" },
      { name: "Paddy Considine", role: "King Viserys" },
    ],
  },
  {
    id: "the-witcher",
    type: "tv",
    title: "The Witcher",
    year: "2019",
    rating: 8.0,
    runtime: "58m / ep",
    genres: ["Fantasy", "Adventure", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/AoGsDM02UVt0npBA8OvpDcZbaMi.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/foGkPxpw9h8zln81j63mix5B7m8.jpg",
    overview:
      "Geralt of Rivia, a mutated monster hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    tagline: "The worst monsters are the ones we create.",
    creator: "Lauren Schmidt Hissrich",
    status: "Returning",
    seasons: 3,
    episodes: 24,
    cast: [
      { name: "Henry Cavill", role: "Geralt of Rivia" },
      { name: "Anya Chalotra", role: "Yennefer" },
      { name: "Freya Allan", role: "Ciri" },
      { name: "Joey Batey", role: "Jaskier" },
    ],
  },
  {
    id: "arcane",
    type: "tv",
    title: "Arcane",
    year: "2021",
    rating: 9.0,
    runtime: "42m / ep",
    genres: ["Animation", "Action", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/5cvnxEHT3e39DvT6ARw4GNCFrB0.jpg",
    overview:
      "Amid the stark class divide of Piltover and Zaun, two sisters find themselves on opposite sides of a war between magic and technology — in this stunning League of Legends series.",
    tagline: "Some legacies are written in blood.",
    creator: "Christian Linke & Alex Yee",
    status: "Ended",
    seasons: 2,
    episodes: 18,
    cast: [
      { name: "Hailee Steinfeld", role: "Vi" },
      { name: "Ella Purnell", role: "Jinx" },
      { name: "Kevin Alejandro", role: "Jayce" },
      { name: "Harry Lloyd", role: "Viktor" },
    ],
  },
  {
    id: "money-heist",
    type: "tv",
    title: "Money Heist",
    year: "2017",
    rating: 8.2,
    runtime: "45m / ep",
    genres: ["Crime", "Thriller", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    overview:
      "Eight robbers take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out the most audacious heist in history.",
    tagline: "The resistance is on.",
    creator: "Álex Pina",
    status: "Ended",
    seasons: 5,
    episodes: 41,
    cast: [
      { name: "Álvaro Morte", role: "The Professor" },
      { name: "Úrsula Corberó", role: "Tokyo" },
      { name: "Pedro Alonso", role: "Berlin" },
      { name: "Itziar Ituño", role: "Raquel Murillo" },
    ],
  },
  {
    id: "the-crown",
    type: "tv",
    title: "The Crown",
    year: "2016",
    rating: 8.6,
    runtime: "58m / ep",
    genres: ["Drama", "Historical"],
    poster: "https://media.themoviedb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/8VXhcrl5z2I1zEU9X3pkkNrZlD.jpg",
    overview:
      "Following the political rivalries and personal drama of Queen Elizabeth II's reign, this lavish drama chronicles the changing face of the British monarchy.",
    tagline: "Duty. Family. Country.",
    creator: "Peter Morgan",
    status: "Ended",
    seasons: 6,
    episodes: 60,
    cast: [
      { name: "Claire Foy", role: "Queen Elizabeth II" },
      { name: "Olivia Colman", role: "Queen Elizabeth II" },
      { name: "Imelda Staunton", role: "Queen Elizabeth II" },
      { name: "Matt Smith", role: "Prince Philip" },
    ],
  },
  {
    id: "dark",
    type: "tv",
    title: "Dark",
    year: "2017",
    rating: 8.7,
    runtime: "52m / ep",
    genres: ["Mystery", "Sci-Fi", "Thriller"],
    poster: "https://media.themoviedb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/3jDXL4Xvj3AzDOF6UH1xeyHW8MH.jpg",
    overview:
      "The disappearance of two children in the small German town of Winden exposes the broken relationships and double lives of four families — and a time travel secret spanning three generations.",
    tagline: "Everything is connected.",
    creator: "Baran bo Odar & Jantje Friese",
    status: "Ended",
    seasons: 3,
    episodes: 26,
    cast: [
      { name: "Louis Hofmann", role: "Jonas Kahnwald" },
      { name: "Lisa Vicari", role: "Martha Nielsen" },
      { name: "Andreas Pietschmann", role: "The Stranger" },
      { name: "Maja Schöne", role: "Hannah Kahnwald" },
    ],
  },
  {
    id: "severance",
    type: "tv",
    title: "Severance",
    year: "2022",
    rating: 8.7,
    runtime: "50m / ep",
    genres: ["Sci-Fi", "Thriller", "Mystery"],
    poster: "https://media.themoviedb.org/t/p/w500/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/ixgFmf1X59PUZam2qbAfskx2gQr.jpg",
    overview:
      "Employees of Lumon Industries undergo a procedure that surgically divides their memories between work and personal lives — until one worker begins to question the truth.",
    tagline: "You have no life outside of work. Literally.",
    creator: "Dan Erickson",
    status: "Returning",
    seasons: 2,
    episodes: 19,
    cast: [
      { name: "Adam Scott", role: "Mark Scout" },
      { name: "Britt Lower", role: "Helly R." },
      { name: "Zach Cherry", role: "Dylan" },
      { name: "John Turturro", role: "Irving" },
    ],
  },
  {
    id: "succession",
    type: "tv",
    title: "Succession",
    year: "2018",
    rating: 8.8,
    runtime: "58m / ep",
    genres: ["Drama", "Comedy"],
    poster: "https://media.themoviedb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/d87JXX3DLkRJMfm5StCmmnmhHuX.jpg",
    overview:
      "The Roy family, owners of a global media empire, fight for control of the company after their aging father begins to consider a successor among his power-hungry children.",
    tagline: "Power is a family business.",
    creator: "Jesse Armstrong",
    status: "Ended",
    seasons: 4,
    episodes: 39,
    cast: [
      { name: "Brian Cox", role: "Logan Roy" },
      { name: "Jeremy Strong", role: "Kendall Roy" },
      { name: "Sarah Snook", role: "Shiv Roy" },
      { name: "Kieran Culkin", role: "Roman Roy" },
    ],
  },
  {
    id: "ted-lasso",
    type: "tv",
    title: "Ted Lasso",
    year: "2020",
    rating: 8.8,
    runtime: "31m / ep",
    genres: ["Comedy", "Drama", "Sports"],
    poster: "https://media.themoviedb.org/t/p/w500/uRHsiw1wLxPHFXkkv4Ix1s0O6f4.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/nE94ejEbzNCU48bW1oju0dqBONz.jpg",
    overview:
      "An American football coach is hired to manage an English Premier League soccer team — despite knowing absolutely nothing about the sport. Everyone is in on the joke except Ted.",
    tagline: "Believe.",
    creator: "Bill Lawrence, Jason Sudeikis & others",
    status: "Ended",
    seasons: 3,
    episodes: 34,
    cast: [
      { name: "Jason Sudeikis", role: "Ted Lasso" },
      { name: "Hannah Waddingham", role: "Rebecca Welton" },
      { name: "Brett Goldstein", role: "Roy Kent" },
      { name: "Juno Temple", role: "Keeley Jones" },
    ],
  },
  {
    id: "peaky-blinders",
    type: "tv",
    title: "Peaky Blinders",
    year: "2013",
    rating: 8.8,
    runtime: "60m / ep",
    genres: ["Crime", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/dzq83RHwQcnP6WGJ6YkenIqeaa5.jpg",
    overview:
      "After the First World War, Birmingham gangster Tommy Shelby and his family run the feared Peaky Blinders crime gang — and set their sights on expanding their empire.",
    tagline: "By order of the Peaky Blinders.",
    creator: "Steven Knight",
    status: "Ended",
    seasons: 6,
    episodes: 36,
    cast: [
      { name: "Cillian Murphy", role: "Tommy Shelby" },
      { name: "Helen McCrory", role: "Polly Gray" },
      { name: "Paul Anderson", role: "Arthur Shelby" },
      { name: "Tom Hardy", role: "Alfie Solomons" },
    ],
  },
  {
    id: "the-last-of-us",
    type: "tv",
    title: "The Last of Us",
    year: "2023",
    rating: 8.7,
    runtime: "55m / ep",
    genres: ["Drama", "Horror", "Action"],
    poster: "https://media.themoviedb.org/t/p/w500/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/lY2DhbA7Hy44fAKddr06UrXWWaQ.jpg",
    overview:
      "Survivor Joel is hired to smuggle fourteen-year-old Ellie out of a quarantine zone twenty years after a devastating fungal pandemic ravaged civilization.",
    tagline: "When you're lost in the darkness, look for the light.",
    creator: "Craig Mazin & Neil Druckmann",
    status: "Returning",
    seasons: 2,
    episodes: 16,
    cast: [
      { name: "Pedro Pascal", role: "Joel Miller" },
      { name: "Bella Ramsey", role: "Ellie Williams" },
      { name: "Anna Torv", role: "Tess" },
      { name: "Gabriel Luna", role: "Tommy Miller" },
    ],
    featured: true,
  },
  {
    id: "loki",
    type: "tv",
    title: "Loki",
    year: "2021",
    rating: 8.2,
    runtime: "50m / ep",
    genres: ["Sci-Fi", "Superhero", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/q3jHCb4dMfYF6ojikKuHd6LscxC.jpg",
    overview:
      "The God of Mischief escapes his timeline and is recruited by the Time Variance Authority to fix the timeline — and in doing so, uncovers a threat to all reality.",
    tagline: "God of outcasts.",
    creator: "Michael Waldron",
    status: "Ended",
    seasons: 2,
    episodes: 12,
    cast: [
      { name: "Tom Hiddleston", role: "Loki" },
      { name: "Sophia Di Martino", role: "Sylvie" },
      { name: "Owen Wilson", role: "Mobius M. Mobius" },
      { name: "Gugu Mbatha-Raw", role: "Ravonna Renslayer" },
    ],
  },
  {
    id: "the-boys",
    type: "tv",
    title: "The Boys",
    year: "2019",
    rating: 8.4,
    runtime: "60m / ep",
    genres: ["Action", "Comedy", "Superhero"],
    poster: "https://media.themoviedb.org/t/p/w500/in1R2dDc421JxsoRWaIIAqVI2KE.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/n6vVs6z8obNbExdD3QHTr4Utu1Z.jpg",
    overview:
      "In a world where superheroes are corrupt celebrities beloved by the public, a group of vigilantes sets out to expose and take down the most powerful 'heroes' for good.",
    tagline: "Never meet your heroes.",
    creator: "Eric Kripke",
    status: "Returning",
    seasons: 4,
    episodes: 32,
    cast: [
      { name: "Karl Urban", role: "Billy Butcher" },
      { name: "Jack Quaid", role: "Hughie Campbell" },
      { name: "Antony Starr", role: "Homelander" },
      { name: "Erin Moriarty", role: "Annie January" },
    ],
  },
  {
    id: "black-mirror",
    type: "tv",
    title: "Black Mirror",
    year: "2011",
    rating: 8.7,
    runtime: "60m / ep",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/dg3OindVAGZBjlT3xYKqIAdukPL.jpg",
    overview:
      "An anthology series that explores a twisted, high-tech near-future where humanity's greatest innovations and darkest instincts collide.",
    tagline: "The future is bright.",
    creator: "Charlie Brooker",
    status: "Ended",
    seasons: 6,
    episodes: 32,
    cast: [
      { name: "Various", role: "Anthology cast" },
      { name: "Jesse Plemons", role: "Navy Seals (multiple eps)" },
      { name: "Bryce Dallas Howard", role: "Lacie Pound (Nosedive)" },
      { name: "Miley Cyrus", role: "Ashley O (Rachel, Jack and Ashley Too)" },
    ],
  },
  {
    id: "better-call-saul",
    type: "tv",
    title: "Better Call Saul",
    year: "2015",
    rating: 9.0,
    runtime: "46m / ep",
    genres: ["Crime", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/rfxryDIv8huejujg4JueDJx8zCz.jpg",
    overview:
      "Six years before meeting Walter White, small-time lawyer Jimmy McGill turns to the criminal underworld — becoming the morally flexible Saul Goodman.",
    tagline: "Better call Saul.",
    creator: "Vince Gilligan & Peter Gould",
    status: "Ended",
    seasons: 6,
    episodes: 63,
    cast: [
      { name: "Bob Odenkirk", role: "Jimmy McGill" },
      { name: "Rhea Seehorn", role: "Kim Wexler" },
      { name: "Jonathan Banks", role: "Mike Ehrmantraut" },
      { name: "Michael McKean", role: "Chuck McGill" },
    ],
  },
  {
    id: "true-detective",
    type: "tv",
    title: "True Detective",
    year: "2014",
    rating: 8.9,
    runtime: "55m / ep",
    genres: ["Crime", "Mystery", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/cuV2O5ZyDLHSOWzg3nLVljp1ubw.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/v8YFr8BbU9qsO8PYIulzTeM6Qk.jpg",
    overview:
      "Detectives Rust Cohle and Marty Hart investigate a ritualistic murder in Louisiana that haunts them for seventeen years — in this acclaimed anthology crime drama.",
    tagline: "Touch darkness and darkness touches you back.",
    creator: "Nic Pizzolatto",
    status: "Returning",
    seasons: 4,
    episodes: 30,
    cast: [
      { name: "Matthew McConaughey", role: "Rust Cohle" },
      { name: "Woody Harrelson", role: "Marty Hart" },
      { name: "Michelle Monaghan", role: "Maggie Hart" },
      { name: "Jodie Foster", role: "Liz Danvers" },
    ],
  },
  {
    id: "friends",
    type: "tv",
    title: "Friends",
    year: "1994",
    rating: 8.9,
    runtime: "22m / ep",
    genres: ["Comedy", "Romance"],
    poster: "https://media.themoviedb.org/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    overview:
      "Six young friends navigate life, love and careers in New York City — going from coffee house regulars to family, one laugh at a time.",
    tagline: "There's nothing like a friend.",
    creator: "David Crane & Marta Kauffman",
    status: "Ended",
    seasons: 10,
    episodes: 236,
    cast: [
      { name: "Jennifer Aniston", role: "Rachel Green" },
      { name: "Courteney Cox", role: "Monica Geller" },
      { name: "Lisa Kudrow", role: "Phoebe Buffay" },
      { name: "Matt LeBlanc", role: "Joey Tribbiani" },
      { name: "Matthew Perry", role: "Chandler Bing" },
      { name: "David Schwimmer", role: "Ross Geller" },
    ],
  },
  {
    id: "the-big-bang-theory",
    type: "tv",
    title: "The Big Bang Theory",
    year: "2007",
    rating: 8.1,
    runtime: "22m / ep",
    genres: ["Comedy"],
    poster: "https://media.themoviedb.org/t/p/w500/euKFiO5M125rpngFRBbSW83beeI.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/rwYvhVv0vwbulMwxOfEsuAr1JrT.jpg",
    overview:
      "Brilliant physicists Leonard and Sheldon meet their new neighbor Penny, a beautiful waitress — and their genius, socially awkward lives are turned hilariously upside down.",
    tagline: "Smart is the new sexy.",
    creator: "Chuck Lorre & Bill Prady",
    status: "Ended",
    seasons: 12,
    episodes: 279,
    cast: [
      { name: "Jim Parsons", role: "Sheldon Cooper" },
      { name: "Johnny Galecki", role: "Leonard Hofstadter" },
      { name: "Kaley Cuoco", role: "Penny" },
      { name: "Simon Helberg", role: "Howard Wolowitz" },
    ],
  },
  // ───────────────────────── ANIME ─────────────────────────
  {
    id: "attack-on-titan",
    type: "anime",
    title: "Attack on Titan",
    year: "2013",
    rating: 9.2,
    runtime: "24m / ep",
    genres: ["Action", "Drama", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
    overview:
      "Humanity cowers behind enormous walls to keep out the man-eating Titans — until a colossal breach forces young Eren Yeager to join the Survey Corps and fight back.",
    tagline: "To defeat the Titans, you must become a monster.",
    creator: "Hajime Isayama",
    status: "Ended",
    seasons: 4,
    episodes: 89,
    cast: [
      { name: "Yuki Kaji", role: "Eren Yeager" },
      { name: "Yui Ishikawa", role: "Mikasa Ackerman" },
      { name: "Marina Inoue", role: "Armin Arlert" },
      { name: "Hiroshi Kamiya", role: "Levi" },
    ],
    featured: true,
  },
  {
    id: "demon-slayer",
    type: "anime",
    title: "Demon Slayer",
    year: "2019",
    rating: 8.7,
    runtime: "24m / ep",
    genres: ["Action", "Fantasy", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg",
    overview:
      "After his family is slaughtered and his sister is turned into a demon, Tanjiro Kamado joins the Demon Slayer Corps to find a cure and avenge his family.",
    tagline: "Set your heart ablaze.",
    creator: "Koyoharu Gotouge",
    status: "Returning",
    seasons: 4,
    episodes: 55,
    cast: [
      { name: "Natsuki Hanae", role: "Tanjiro Kamado" },
      { name: "Akari Kito", role: "Nezuko Kamado" },
      { name: "Hiro Shimono", role: "Zenitsu Agatsuma" },
      { name: "Yoshitsugu Matsuoka", role: "Inosuke Hashibira" },
    ],
  },
  {
    id: "jujutsu-kaisen",
    type: "anime",
    title: "Jujutsu Kaisen",
    year: "2020",
    rating: 8.6,
    runtime: "24m / ep",
    genres: ["Action", "Fantasy", "Supernatural"],
    poster: "https://media.themoviedb.org/t/p/w500/6qQzMJG27XOJsyAEEIisoJB45j2.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/qpin8cASXEVtwhzNsprHYFiOAGk.jpg",
    overview:
      "To save his friends from a cursed spirit, Yuji Itadori swallows a rotting finger and inherits a demon's power — joining a school of sorcerers to hunt curses.",
    tagline: "Curse these hands.",
    creator: "Gege Akutami",
    status: "Returning",
    seasons: 2,
    episodes: 47,
    cast: [
      { name: "Junya Enoki", role: "Yuji Itadori" },
      { name: "Yuuma Uchida", role: "Megumi Fushiguro" },
      { name: "Asami Seto", role: "Nobara Kugisaki" },
      { name: "Kenjiro Tsuda", role: "Nanami Kento" },
    ],
  },
  {
    id: "one-piece",
    type: "anime",
    title: "One Piece",
    year: "1999",
    rating: 8.7,
    runtime: "24m / ep",
    genres: ["Adventure", "Action", "Comedy"],
    poster: "https://media.themoviedb.org/t/p/w500/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
    overview:
      "Monkey D. Luffy sets sail with his pirate crew in search of the legendary One Piece treasure, aiming to become the King of the Pirates.",
    tagline: "The Pirate King is waiting.",
    creator: "Eiichiro Oda",
    status: "Returning",
    seasons: 21,
    episodes: 1100,
    cast: [
      { name: "Mayumi Tanaka", role: "Monkey D. Luffy" },
      { name: "Kazuya Nakai", role: "Roronoa Zoro" },
      { name: "Akemi Okamura", role: "Nami" },
      { name: "Kappei Yamaguchi", role: "Sanji" },
    ],
  },
  {
    id: "naruto-shippuden",
    type: "anime",
    title: "Naruto Shippuden",
    year: "2007",
    rating: 8.7,
    runtime: "23m / ep",
    genres: ["Action", "Adventure", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/kV27j3Nz4d5z8u6mN3EJw9RiLg2.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/z0YhJvomqedHF85bplUJEotkN5l.jpg",
    overview:
      "Two and a half years after leaving the Hidden Leaf Village, Naruto Uzumaki returns stronger — and ready to face growing threats while chasing his dream of becoming Hokage.",
    tagline: "Hard work beats talent.",
    creator: "Masashi Kishimoto",
    status: "Ended",
    seasons: 21,
    episodes: 500,
    cast: [
      { name: "Junko Takeuchi", role: "Naruto Uzumaki" },
      { name: "Noriaki Sugiyama", role: "Sasuke Uchiha" },
      { name: "Chie Nakamura", role: "Sakura Haruno" },
      { name: "Kazuhiko Inoue", role: "Kakashi Hatake" },
    ],
  },
  {
    id: "fullmetal-alchemist-brotherhood",
    type: "anime",
    title: "Fullmetal Alchemist: Brotherhood",
    year: "2009",
    rating: 9.1,
    runtime: "24m / ep",
    genres: ["Action", "Adventure", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/A6tMQAo6t6eRFCPhsrShmxZLqFB.jpg",
    overview:
      "Two brothers use alchemy in search of the Philosopher's Stone to restore their bodies — and in doing so, uncover a conspiracy that spans an entire nation.",
    tagline: "Everything has a price.",
    creator: "Hiromu Arakawa",
    status: "Ended",
    seasons: 5,
    episodes: 64,
    cast: [
      { name: "Romi Park", role: "Edward Elric" },
      { name: "Rie Kugimiya", role: "Alphonse Elric" },
      { name: "Shinichiro Miki", role: "Roy Mustang" },
      { name: "Megumi Takamoto", role: "Winry Rockbell" },
    ],
    featured: true,
  },
  {
    id: "one-punch-man",
    type: "anime",
    title: "One-Punch Man",
    year: "2015",
    rating: 8.7,
    runtime: "24m / ep",
    genres: ["Action", "Comedy", "Sci-Fi"],
    poster: "https://media.themoviedb.org/t/p/w500/dT10AxJIXVvRwFAew4tt2RhzJrD.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/s0w8JbuNNxL1YgaHeDWih12C3jG.jpg",
    overview:
      "Saitama can defeat any foe with a single punch — which makes being a hero tremendously boring. He searches for a worthy opponent to make his life exciting again.",
    tagline: "One punch is all it takes.",
    creator: "ONE & Yusuke Murata",
    status: "Returning",
    seasons: 2,
    episodes: 24,
    cast: [
      { name: "Makoto Furukawa", role: "Saitama" },
      { name: "Kaito Ishikawa", role: "Genos" },
      { name: "Hikari Yano", role: "Tornado of Terror" },
      { name: "Aoi Yuki", role: "Tatsumaki" },
    ],
  },
  {
    id: "chainsaw-man",
    type: "anime",
    title: "Chainsaw Man",
    year: "2022",
    rating: 8.5,
    runtime: "24m / ep",
    genres: ["Action", "Fantasy", "Horror"],
    poster: "https://media.themoviedb.org/t/p/w500/iFM1dyFi0rByvEomEkmm7NpQeeb.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg",
    overview:
      "A poverty-stricken young man merges with his chainsaw devil dog and becomes Chainsaw Man — a hybrid creature hunted by devils, monsters and a secret government agency.",
    tagline: "His heart is a chainsaw.",
    creator: "Tatsuki Fujimoto",
    status: "Returning",
    seasons: 1,
    episodes: 12,
    cast: [
      { name: "Kikunosuke Toya", role: "Denji" },
      { name: "Fairouz Ai", role: "Power" },
      { name: "Tomori Kusunoki", role: "Makima" },
      { name: "Shogo Sakata", role: "Aki Hayakawa" },
    ],
  },
  {
    id: "spy-x-family",
    type: "anime",
    title: "Spy x Family",
    year: "2022",
    rating: 8.5,
    runtime: "24m / ep",
    genres: ["Comedy", "Action", "Slice of Life"],
    poster: "https://media.themoviedb.org/t/p/w500/7NAvPYPAu7MeHwP8E9sn81PqsRh.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/lysUnU6V0VfcthDbviuVlIqgHOR.jpg",
    overview:
      "A master spy creates a fake family as cover for his mission — unaware that his wife is an assassin and his adopted daughter is a telepath. Chaos ensues by the dinner table.",
    tagline: "Operation family.",
    creator: "Tatsuya Endo",
    status: "Returning",
    seasons: 3,
    episodes: 37,
    cast: [
      { name: "Takuya Eguchi", role: "Loid Forger" },
      { name: "Saori Hayami", role: "Yor Forger" },
      { name: "Atsumi Tanezaki", role: "Anya Forger" },
      { name: "Kenichiro Matsuda", role: "Bond Forger" },
    ],
  },
  {
    id: "my-hero-academia",
    type: "anime",
    title: "My Hero Academia",
    year: "2016",
    rating: 8.3,
    runtime: "24m / ep",
    genres: ["Action", "Superhero", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/ol0H2DGp4ifBHA4JDlCpwJWxnY2.jpg",
    overview:
      "In a world where nearly everyone has a superpower, born-quirkless Izuku Midoriya inherits the power of the world's greatest hero and enrolls in U.A. High.",
    tagline: "Go beyond, Plus Ultra!",
    creator: "Kohei Horikoshi",
    status: "Returning",
    seasons: 7,
    episodes: 159,
    cast: [
      { name: "Daiki Yamashita", role: "Izuku Midoriya" },
      { name: "Kenta Miyake", role: "All Might" },
      { name: "Nobuhiko Okamoto", role: "Katsuki Bakugo" },
      { name: "Yuki Kaji", role: "Shoto Todoroki" },
    ],
  },
  {
    id: "your-name",
    type: "anime",
    title: "Your Name",
    year: "2016",
    rating: 8.8,
    runtime: "1h 46m",
    genres: ["Romance", "Fantasy", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/vfJFJPepRKapMd5G2ro7klIRysq.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg",
    overview:
      "Two strangers — a Tokyo boy and a countryside girl — find themselves mysteriously switching bodies. As they grow closer across time and space, a cosmic secret unravels.",
    tagline: "The one thing I'm certain of is that I'll find you.",
    creator: "Makoto Shinkai",
    status: "Film",
    cast: [
      { name: "Ryunosuke Kamiki", role: "Taki Tachibana" },
      { name: "Mone Kamishiraishi", role: "Mitsuha Miyamizu" },
      { name: "Masami Nagasawa", role: "Miki Okudera" },
      { name: "Etsuko Ichihara", role: "Hitoha Miyamizu" },
    ],
  },
  {
    id: "spirited-away",
    type: "anime",
    title: "Spirited Away",
    year: "2001",
    rating: 8.6,
    runtime: "2h 5m",
    genres: ["Fantasy", "Adventure", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
    overview:
      "When her parents are turned into pigs by a witch, young Chihiro must work in a bathhouse for spirits to find a way to free them — and discover her own courage.",
    tagline: "A world of gods, spirits and creatures.",
    creator: "Hayao Miyazaki",
    status: "Film",
    cast: [
      { name: "Rumi Hiiragi", role: "Chihiro Ogino" },
      { name: "Miyu Irino", role: "Haku" },
      { name: "Mari Natsuki", role: "Yubaba" },
      { name: "Takashi Naito", role: "Father" },
    ],
  },
  {
    id: "cowboy-bebop",
    type: "anime",
    title: "Cowboy Bebop",
    year: "1998",
    rating: 8.7,
    runtime: "24m / ep",
    genres: ["Sci-Fi", "Action", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/xDiXDfZwC6XYC6fxHI1jl3A3Ill.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/A4PHx94G7mvM3b8vsDJ5HEaQ6uv.jpg",
    overview:
      "A ragtag crew of bounty hunters chase criminals across the solar system in the spaceship Bebop — each one running from a past they can't escape.",
    tagline: "See you, space cowboy.",
    creator: "Shinichiro Watanabe",
    status: "Ended",
    seasons: 1,
    episodes: 26,
    cast: [
      { name: "Koichi Yamadera", role: "Spike Spiegel" },
      { name: "Unsho Ishizuka", role: "Jet Black" },
      { name: "Megumi Hayashibara", role: "Faye Valentine" },
      { name: "Aoi Tada", role: "Edward Wong" },
    ],
  },
  {
    id: "akira",
    type: "anime",
    title: "Akira",
    year: "1988",
    rating: 8.0,
    runtime: "2h 4m",
    genres: ["Sci-Fi", "Action", "Thriller"],
    poster: "https://media.themoviedb.org/t/p/w500/neZ0ykEsPqxamsX6o5QNUFILQrz.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/fK40VGYIm7hmKrLJ26fgPQU0qRG.jpg",
    overview:
      "In a dystopian Neo-Tokyo, biker gang leader Kaneda tries to save his friend Tetsuo, whose untapped psychic powers begin to consume him — and threaten the entire city.",
    tagline: "The chaos is coming.",
    creator: "Katsuhiro Otomo",
    status: "Film",
    cast: [
      { name: "Mitsuo Iwata", role: "Shotaro Kaneda" },
      { name: "Nozomu Sasaki", role: "Tetsuo Shima" },
      { name: "Mami Koyama", role: "Kei" },
      { name: "Tessho Genda", role: "The Joker" },
    ],
  },
  {
    id: "princess-mononoke",
    type: "anime",
    title: "Princess Mononoke",
    year: "1997",
    rating: 8.4,
    runtime: "2h 14m",
    genres: ["Fantasy", "Adventure", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg",
    overview:
      "A prince caught between an iron-mining colony and the forest gods embarks on a quest to find a cure — and forges a bond with a young woman raised by wolves.",
    tagline: "The fate of the world rests on the courage of one.",
    creator: "Hayao Miyazaki",
    status: "Film",
    cast: [
      { name: "Yōji Matsuda", role: "Ashitaka" },
      { name: "Yuriko Ishida", role: "San" },
      { name: "Akihiro Miwa", role: "Moro" },
      { name: "Billy Crudup", role: "Ashitaka (EN)" },
    ],
  },
  {
    id: "demon-slayer-mugen-train",
    type: "anime",
    title: "Demon Slayer: Mugen Train",
    year: "2020",
    rating: 8.2,
    runtime: "1h 56m",
    genres: ["Action", "Fantasy", "Adventure"],
    poster: "https://media.themoviedb.org/t/p/w500/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/qjGrUmKW78MCFG8PTLDBp67S27p.jpg",
    overview:
      "Tanjiro and his friends board the mysterious Mugen Train, where Flame Hashira Rengoku joins the fight against a demon who preys on dreamers.",
    tagline: "Set your heart ablaze.",
    creator: "Koyoharu Gotouge",
    status: "Film",
    cast: [
      { name: "Natsuki Hanae", role: "Tanjiro Kamado" },
      { name: "Satoshi Hino", role: "Kyojuro Rengoku" },
      { name: "Akari Kito", role: "Nezuko Kamado" },
      { name: "Hiro Shimono", role: "Zenitsu Agatsuma" },
    ],
  },
  {
    id: "attack-on-titan-1",
    type: "anime",
    title: "Attack on Titan: The Final Season",
    year: "2020",
    rating: 9.1,
    runtime: "24m / ep",
    genres: ["Action", "Drama", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
    overview:
      "The final chapter of the saga sees Eren and his friends confront the truth about the world beyond the walls — and the terrible price of freedom.",
    tagline: "War for Paradise.",
    creator: "Hajime Isayama",
    status: "Ended",
    seasons: 1,
    episodes: 28,
    cast: [
      { name: "Yuki Kaji", role: "Eren Yeager" },
      { name: "Yui Ishikawa", role: "Mikasa Ackerman" },
      { name: "Marina Inoue", role: "Armin Arlert" },
      { name: "Hiroshi Kamiya", role: "Levi" },
    ],
  },
  {
    id: "hunter-x-hunter",
    type: "anime",
    title: "Hunter x Hunter",
    year: "2011",
    rating: 9.0,
    runtime: "24m / ep",
    genres: ["Action", "Adventure", "Fantasy"],
    poster: "https://media.themoviedb.org/t/p/w500/i2EEr2uBvRlAwJ8d8zTG2Y19mIa.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/bFKKyCI89Xq98Gul8cGox8K3sZa.jpg",
    overview:
      "Gon Freecss leaves home to pass the Hunter Exam — an elite license that grants access to hidden worlds-monsters, fortunes, and the search for his missing father.",
    tagline: "The ultimate adventure begins.",
    creator: "Yoshihiro Togashi",
    status: "Ended",
    seasons: 6,
    episodes: 148,
    cast: [
      { name: "Megumi Han", role: "Gon Freecss" },
      { name: "Mariya Ise", role: "Killua Zoldyck" },
      { name: "Issei Futamata", role: "Leorio Paladiknight" },
      { name: "Daisuke Namikawa", role: "Kurapika" },
    ],
  },
  {
    id: "steins-gate",
    type: "anime",
    title: "Steins;Gate",
    year: "2011",
    rating: 9.0,
    runtime: "24m / ep",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/96R4bV7dB8ramaWceNKsxvJgCUd.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/gDvxT2z6TNxervG97WfpePRZ3aR.jpg",
    overview:
      "Self-proclaimed mad scientist Okabe Rintaro accidentally discovers that his hobby gadget can send messages to the past — and learns that tampering with time has a cost.",
    tagline: "El Psy Kongroo.",
    creator: "White Fox",
    status: "Ended",
    seasons: 1,
    episodes: 24,
    cast: [
      { name: "Mamoru Miyano", role: "Okabe Rintaro" },
      { name: "Asami Imai", role: "Makise Kurisu" },
      { name: "Kana Hanazawa", role: "Mayuri Shiina" },
      { name: "Tomokazu Seki", role: "Itaru Hashida" },
    ],
  },
  {
    id: "neon-genesis-evangelion",
    type: "anime",
    title: "Neon Genesis Evangelion",
    year: "1995",
    rating: 8.6,
    runtime: "24m / ep",
    genres: ["Sci-Fi", "Drama", "Mecha"],
    poster: "https://media.themoviedb.org/t/p/w500/y2ah9t0navXyIvoHg1uIbIHO3tt.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/awR8ZpAmieF0Pnc1AXxcCbEUjug.jpg",
    overview:
      "In the aftermath of a cataclysmic event, teenage pilots control giant bio-mechs to defend Neo Tokyo from the mysterious Angels — while wrestling with their own trauma.",
    tagline: "Get in the robot, Shinji.",
    creator: "Hideaki Anno",
    status: "Ended",
    seasons: 1,
    episodes: 26,
    cast: [
      { name: "Megumi Ogata", role: "Shinji Ikari" },
      { name: "Megumi Hayashibara", role: "Rei Ayanami" },
      { name: "Yuko Miyamura", role: "Asuka Langley" },
      { name: "Kotono Mitsuishi", role: "Misato Katsuragi" },
    ],
  },
  {
    id: "frieren-beyond-journeys-end",
    type: "anime",
    title: "Frieren: Beyond Journey's End",
    year: "2023",
    rating: 9.3,
    runtime: "24m / ep",
    genres: ["Fantasy", "Adventure", "Drama"],
    poster: "https://media.themoviedb.org/t/p/w500/dqZENchTd7lp5zht7BdlqM7RBhD.jpg",
    backdrop: "https://media.themoviedb.org/t/p/w1280/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg",
    overview:
      "After the demon king is defeated, elven mage Frieren — whose lifespan spans centuries — embarks on a journey of memory and meaning long after her mortal companions fade.",
    tagline: "The end of the journey is just the beginning.",
    creator: "Kanehito Yamada",
    status: "Returning",
    seasons: 1,
    episodes: 28,
    cast: [
      { name: "Atsumi Tanezaki", role: "Frieren" },
      { name: "Nobuhiko Okamoto", role: "Himmel" },
      { name: "Kana Ichinose", role: "Fern" },
      { name: "Chiaki Kobayashi", role: "Stark" },
    ],
  },
];

export function getTitle(id: string): Title | undefined {
  return titles.find((t) => t.id === id);
}

export function getFeatured(): Title[] {
  return titles.filter((t) => t.featured);
}

export function searchTitles(
  query: string,
  type?: string,
  genre?: string,
  sort?: string,
): Title[] {
  const q = query.trim().toLowerCase();
  let results = titles.filter((t) => {
    if (type && t.type !== type) return false;
    if (genre && !t.genres.includes(genre)) return false;
    if (!q) return true;
    return (
      t.title.toLowerCase().includes(q) ||
      t.genres.some((g) => g.toLowerCase().includes(q)) ||
      t.overview.toLowerCase().includes(q) ||
      t.cast.some((c) => c.name.toLowerCase().includes(q))
    );
  });

  switch (sort) {
    case "rating":
      results = [...results].sort((a, b) => b.rating - a.rating);
      break;
    case "year":
      results = [...results].sort((a, b) => b.year.localeCompare(a.year));
      break;
    case "title":
      results = [...results].sort((a, b) => a.title.localeCompare(b.title));
      break;
    default:
      results = [...results].sort((a, b) => b.rating - a.rating);
  }
  return results;
}